env:
  - RUNNING_CI=1
sudo: false
language: python

matrix:
  include:
   - os: linux
     dist: trusty
     python:
       - "2.6"
   - os: linux
     dist: xenial
     python: 
       - "2.7"
   - os: linux
     dist: xenial
     python: 
       - "3.4"
   - os: linux
     dist: xenial
     python: 
       - "3.5"
   - os: linux
     dist: xenial
     python: 
       - "3.6"
   - os: linux
     dist: xenial
     python: 
       - "3.7"
install: pip install tox-travis
script: tox
