#!/usr/bin/env python

import sys, os

FUNCTION_PATH = os.path.abspath(os.path.dirname(__file__) + "/functions")
sys.path.append(FUNCTION_PATH+"/general_py")

import esm_master


if __name__ == "__main__":
    # os.system("functions/general_py/esm_master.py "+sys.argv[1:])
    esm_master.main(sys.argv[1:])
