class oasis:
    def __init__(self, nb_of_couplings = 1, coupled_execs = ["echam", "fesom"], runtime = 1, debug_level=1):
        self.namcouple = ["# This namcouple was automatically generated by the easy-scripts"]
        self.namcouple += [" $NFIELDS", "        " + str(nb_of_couplings), "$END"]
        exec_entry = ""
        for exe in coupled_execs:
            exec_entry = exec_entry + " " + exe
        exec_entry = str(len(coupled_execs)) + exec_entry
        self.namcouple += [" $NBMODEL", "        " + str(exec_entry), "$END"]
        self.namcouple += [" $RUNTIME", "        " + str(runtime), "$END"]
        self.namcouple += [" $LOGPRT", "        " + str(debug_level), "$END"]
        self.namcouple += [" $STRINGS"]
        self.namcouple += ["###############################################################################"]
        self.namcouple += ["###############################################################################"]

    def add_coupling(self, lefts, rights):
        self.namcouple += ["#"]

        left = sep = ""
        for lefty in lefts:
            left += sep + lefty
            sep = ":"

        self.namcouple += [left + " " + right]

        self.namcouple += ["#"]
        self.namcouple += ["#"]
        self.namcouple += ["#"]
        self.namcouple += ["###############################################################################"]

    def finalize(self, destination_dir):
        self.namcouple += [" $END"]
        endline=""
        with open(destination_dir+"/namcouple", "w") as namcouple:
            for line in self.namcouple:
                namcouple.write(endline)
                namcouple.write(line)
                endline="\n"



	
