sudo: true
language: python
matrix:
  include:
  - python: 2.6
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
    dist: xenial
  - python: pypy
  - os: osx
    language: generic
install:
  - scripts/travis.sh pip install --upgrade setuptools
  - scripts/travis.sh pip install --upgrade --constraint=constraints.txt --requirement=requirements-travis.txt
  - scripts/travis.sh LC_ALL=C pip install .
script:
  - scripts/travis.sh make check
  - scripts/travis.sh make test
after_success:
  - scripts/travis.sh coveralls
branches:
  except:
    - /^[0-9]/
